# Basic site config
title: "Umang Sharma"
description: "Portfolio"
url: "https://umangsharmacs.github.io"
baseurl: ""

# Use GitHub Pages supported theme
theme: minima

# Optional, but recommended
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Show Projects in the top nav
header_pages:
  - projects.md

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  experience:
    output: true
    permalink: /experience/:name/
  cards:
    output: false

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "experience"
    values:
      layout: "experience"

